### ISSUE TITLE
getting old version to work on 1.7.10

### ISSUE THREAD

**Issue by Skyior** [APDevTeam/Movecraft#185]
**No movement**
So far I have an old build of the plugin that successfully loads on my server. I can build any ship, it will recognize the blocks in it, allow me to start piloting, and will even consume fuel when attempting to move. I get notifications when I go overboard, and even when blocks get destroyed and it's supposed to start sinking. the helm sign will transform into the steering wheel... overall it seems like everything is working EXCEPT any movement. Nothing is moving.

**The error**
Every time I start piloting the craft this thread appears in my server log

[16:54:01] [Server thread/INFO]: [Movecraft] Player Aronix12 piloted a craft of type Airskiff with size 23 at location: -1625 x, 991 z
[16:54:03] [Server thread/WARN]: [Movecraft] Task #74 for Movecraft v3.1.X80 generated an exception
java.lang.NoSuchMethodError: at.pavlov.cannons.API.CannonsAPI.getCannons(Ljava/util/List;Ljava/util/UUID;Z)Ljava/util/HashSet;
	at net.countercraft.movecraft.async.AsyncManager.processAlgorithmQueue(AsyncManager.java:262) ~[?:?]
	at net.countercraft.movecraft.async.AsyncManager.run(AsyncManager.java:857) ~[?:?]
	at org.bukkit.craftbukkit.v1_7_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-1543]
	at org.bukkit.craftbukkit.v1_7_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:346) [spigot.jar:git-Spigot-1543]
	at net.minecraft.server.v1_7_R3.MinecraftServer.v(MinecraftServer.java:638) [spigot.jar:git-Spigot-1543]
	at net.minecraft.server.v1_7_R3.DedicatedServer.v(DedicatedServer.java:284) [spigot.jar:git-Spigot-1543]
	at net.minecraft.server.v1_7_R3.MinecraftServer.u(MinecraftServer.java:584) [spigot.jar:git-Spigot-1543]
	at net.minecraft.server.v1_7_R3.MinecraftServer.run(MinecraftServer.java:490) [spigot.jar:git-Spigot-1543]
	at net.minecraft.server.v1_7_R3.ThreadServerApplication.run(SourceFile:628) [spigot.jar:git-Spigot-1543]

**Screenshots**
![Screenshot (5)](https://user-images.githubusercontent.com/52142131/68512334-b61f8100-023d-11ea-8959-5a8a057648af.png)

![Screenshot (4)](https://user-images.githubusercontent.com/52142131/68512360-c9cae780-023d-11ea-8c3d-638962314e8b.png)

**Versions :**
 - Movecraft: v3.1.X80
 - Minecraft 1.7.10

**Comment by cccm5** [comment]
I don't about about such an old version, but perhaps try adding an older version of the cannons plugin
